// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface NodeJsCreateSessionRequest {
    /** Custom session ID (auto-generated if not provided) */
    session_id?: string;
    /** Working directory for the session */
    cwd?: string;
    /** Maximum idle time in seconds (default 24 hours) */
    max_idle_time?: number;
}
