// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface NodeJsUpdateSessionRequest {
    /** New maximum idle time in seconds */
    max_idle_time?: number;
    /** New working directory */
    cwd?: string;
}
