// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace File_ {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class File_ {
    protected readonly _options: File_.Options;

    constructor(_options: File_.Options) {
        this._options = _options;
    }

    /**
     * Read file content
     *
     * @param {Sandbox.FileReadRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.readFile({
     *         file: "file"
     *     })
     */
    public readFile(
        request: Sandbox.FileReadRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileReadResult, Sandbox.file.readFile.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__readFile(request, requestOptions));
    }

    private async __readFile(
        request: Sandbox.FileReadRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileReadResult, Sandbox.file.readFile.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/read",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileReadResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.readFile.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.readFile.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Write file content (supports both text and binary files)
     *
     * For binary files, set encoding to 'base64' and provide base64-encoded content.
     * For text files, use default 'utf-8' encoding.
     *
     * @param {Sandbox.FileWriteRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.writeFile({
     *         file: "file",
     *         content: "content"
     *     })
     */
    public writeFile(
        request: Sandbox.FileWriteRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileWriteResult, Sandbox.file.writeFile.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__writeFile(request, requestOptions));
    }

    private async __writeFile(
        request: Sandbox.FileWriteRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileWriteResult, Sandbox.file.writeFile.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/write",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileWriteResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.writeFile.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.writeFile.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Replace string in file
     *
     * @param {Sandbox.FileReplaceRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.replaceInFile({
     *         file: "file",
     *         old_str: "old_str",
     *         new_str: "new_str"
     *     })
     */
    public replaceInFile(
        request: Sandbox.FileReplaceRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileReplaceResult, Sandbox.file.replaceInFile.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__replaceInFile(request, requestOptions));
    }

    private async __replaceInFile(
        request: Sandbox.FileReplaceRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileReplaceResult, Sandbox.file.replaceInFile.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/replace",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileReplaceResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.replaceInFile.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.replaceInFile.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Search in file content
     *
     * @param {Sandbox.FileSearchRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.searchInFile({
     *         file: "file",
     *         regex: "regex"
     *     })
     */
    public searchInFile(
        request: Sandbox.FileSearchRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileSearchResult, Sandbox.file.searchInFile.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__searchInFile(request, requestOptions));
    }

    private async __searchInFile(
        request: Sandbox.FileSearchRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileSearchResult, Sandbox.file.searchInFile.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/search",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileSearchResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.searchInFile.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.searchInFile.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Find files by name pattern
     *
     * @param {Sandbox.FileFindRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.findFiles({
     *         path: "path",
     *         glob: "glob"
     *     })
     */
    public findFiles(
        request: Sandbox.FileFindRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileFindResult, Sandbox.file.findFiles.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__findFiles(request, requestOptions));
    }

    private async __findFiles(
        request: Sandbox.FileFindRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileFindResult, Sandbox.file.findFiles.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/find",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileFindResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.findFiles.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.findFiles.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Upload file using streaming
     *
     * @param {Sandbox.BodyUploadFile} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.file.uploadFile({
     *         file: fs.createReadStream("/path/to/your/file")
     *     })
     */
    public uploadFile(
        request: Sandbox.BodyUploadFile,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileUploadResult, Sandbox.file.uploadFile.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__uploadFile(request, requestOptions));
    }

    private async __uploadFile(
        request: Sandbox.BodyUploadFile,
        requestOptions?: File_.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileUploadResult, Sandbox.file.uploadFile.Error>>
    > {
        const _request = await core.newFormData();
        await _request.appendFile("file", request.file);
        if (request.path != null) {
            _request.append("path", request.path);
        }

        const _maybeEncodedRequest = await _request.getRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ..._maybeEncodedRequest.headers }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/upload",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileUploadResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.uploadFile.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.uploadFile.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Download file using FileResponse
     */
    public downloadFile(
        request: Sandbox.FileDownloadFileRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<core.BinaryResponse, Sandbox.file.downloadFile.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__downloadFile(request, requestOptions));
    }

    private async __downloadFile(
        request: Sandbox.FileDownloadFileRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<core.BinaryResponse, Sandbox.file.downloadFile.Error>>> {
        const { path } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.path = path;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/download",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.downloadFile.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.downloadFile.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * List path contents with flexible options
     *
     * @param {Sandbox.FileListRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.listPath({
     *         path: "path"
     *     })
     */
    public listPath(
        request: Sandbox.FileListRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseFileListResult, Sandbox.file.listPath.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__listPath(request, requestOptions));
    }

    private async __listPath(
        request: Sandbox.FileListRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseFileListResult, Sandbox.file.listPath.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseFileListResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.listPath.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.listPath.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * An filesystem editor tool that allows the agent to
     * - view
     * - create
     * - navigate
     * - edit files
     * The tool parameters are defined by Anthropic and are not editable.
     *
     * @param {Sandbox.StrReplaceEditorRequest} request
     * @param {File_.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.file.strReplaceEditor({
     *         command: "view",
     *         path: "path"
     *     })
     */
    public strReplaceEditor(
        request: Sandbox.StrReplaceEditorRequest,
        requestOptions?: File_.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseStrReplaceEditorResult, Sandbox.file.strReplaceEditor.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__strReplaceEditor(request, requestOptions));
    }

    private async __strReplaceEditor(
        request: Sandbox.StrReplaceEditorRequest,
        requestOptions?: File_.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseStrReplaceEditorResult, Sandbox.file.strReplaceEditor.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/file/str_replace_editor",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseStrReplaceEditorResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.file.strReplaceEditor.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.file.strReplaceEditor.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
