// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Response model for browser actions.
 *
 * Provides backward compatibility:
 * - Old format: resp.json()['status'], resp.json()['action_performed']
 * - New format: resp.json()['data']['status'], resp.json()['data']['action_performed']
 */
export interface ActionResponse {
    status: "success";
    action_performed: string;
    data?: Sandbox.ActionData;
}
