// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Browser Info result
 */
export interface BrowserInfoResult {
    /** User agent */
    user_agent: string;
    /** Browser CDP URL */
    cdp_url: string;
    /** VNC URL */
    vnc_url: string;
    /** Viewport size */
    viewport: Sandbox.BrowserViewport;
}
