// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * 将可用工具按功能分类
 */
export interface ToolCategory {
    /** Name of tool category */
    category: string;
    /** List of tools under this category */
    tools: Sandbox.AvailableTool[];
}
